version: "3.8"
services:
  mongodb:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend
    image: yunus05/backend:latest
    env_file:
      - ./backend/.env.docker
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend
    image: yunus05/frontend:latest
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"

volumes:
  data:
